config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'
  
  resources :production_batch_dates, :assays, :assay_batches
  
  resources :assignments do
    resources :corrections
    resources :reassignments
  end
  
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  has_many :corrections, dependent: :delete_all
  has_many :reassignments, dependent: :delete_all
  
  validates_presence_of :assignment_type, :assignment_identifier, :pick_up_time, :assigned_to
  
  def pick_up_time_string
    pick_up_time.to_s
  end
  
  def pick_up_time_string=(pick_up_time_str)
    self.pick_up_time = Chronic.parse(pick_up_time_str)
  rescue ArgumentError
    @pick_up_time_invalid = true
  end
  
  def review_complete_string
    review_complete.to_s
  end
  
  def review_complete_string=(review_complete_str)
    self.review_complete = Chronic.parse(review_complete_str)
  rescue ArgumentError
    @review_complete_invalid = true
  end
  
  def validate
    errors.add(:pick_up_time, "is invalid") if @pick_up_time_invalid
    errors.add(:review_complete, "is invalid") if @review_complete_invalid
  end
  
  def update_assignee_on_reassign!
    self.update_column(:assigned_to, self.reassignments.last.reassigned_to)
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  include ApplicationHelper
  load_and_authorize_resource
  
  helper_method :sort_column, :sort_direction
  
  def index
    @assignment   = Assignment.new
    @assignments  = Assignment.order(sort_column + " " + sort_direction)
    @assayBatches = assay_batch_map.compact
  end
  
  def show
    @assignment    = assignment_find
    @corrections   = Correction.where(assignment_id: @assignment)
    @reassignments = Reassignment.where(assignment_id: @assignment)
  end
  
  def edit
    @assignment   = assignment_find
    @assayBatches = assay_batch_map
  end
  
  def create
    @assignment   = Assignment.new(assignment_params)
    @assignments  = Assignment.all
    @assayBatches = assay_batch_map
    
    if @assignment.save
      redirect_to :back
    else
      render 'index'
    end
  end
  
  def update
    @assignment   = assignment_find
    @assayBatches = assay_batch_map
    
    if @assignment.update(assignment_params)
      if @assignment.status_of == 'Pending'
        @assignment.update(review_complete: nil)
      elsif @assignment.status_of == 'Reassigned' || @assignment.status_of == 'Complete'
        @assignment.update(review_complete: Time.now)
      end
      redirect_to :back  
    else
      render 'edit'
    end
  end
  
  def destroy
    @assignment = assignment_find
    @assignment.destroy
    
    redirect_to :back
  end
  
  private
    def assignment_params
      params.require(:assignment).permit(:assignment_type,
                                         :assignment_identifier,
                                         :pick_up_time,
                                         :pick_up_time_string,
                                         :assigned_to,
                                         :status_of,
                                         :review_complete,
                                         :num_samples,
                                         :notes)
    end
    
    def assignment_find
      Assignment.find_by_id(params[:id])
    end
    
    def assay_batch_map
      current_batch_nums    = ProductionBatchDate.where(batch_date: ((1.days.ago)-2.years..(Date.today + 1)-2.years))
      current_assay_batches = AssayBatch.where(production_batch_date_id: current_batch_nums)
      current_assay_batches.map do |ab|
        [ "#{batch_num(ab.production_batch_date.batch_date)} - #{ab.assay.name}", ab.id ]
      end
    end
    
    def sort_column
      %w[ assignment_type
          assignment_identifier
          pick_up_time
          assigned_to
          status_of
          review_complete].include?(params[:sort]) ? params[:sort] : "pick_up_time"
    end
    
    def sort_direction
     %w[ asc desc ].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
  
  def assignment_batch (assigned)
    batch_num(AssayBatch.find_by_id(assigned.assignment_type).production_batch_date.batch_date)
  end
  
  def assignment_assay (assigned)
    AssayBatch.find_by_id(assigned.assignment_type).assay.name
  end
  
  def assignment_name (assigned)
    "#{assignment_batch(assigned)} - #{assignment_assay(assigned)} #{assigned.assignment_identifier}"
  end
  
  def review_state(date)
    if date
      "Yes"
    else
      "No"
    end
  end
end

app/views/assignments/_form.html.erb
<%= form_for @assignment do |f| %>
  <%= render 'layouts/errors', object: @assignment %>
  <tr>
    <td>
      <%= f.select( :assignment_type,
                    options_for_select(@assayBatches), {},
                    {class: "form-control form-select assignment-input"} ) %>
    </td>
    <td>
      <%= f.text_field  :assignment_identifier,
                        autofocus: true,
                        class: "form-control assignment-input" %>
    </td>
    <td>
      <%= f.text_field :pick_up_time_string,
                        value: (@assignment.pick_up_time.nil? ?
                                  datetime_placeholder :
                                  @assignment.pick_up_time.pretty),
                        class: "form-control assignment-input" %>
    </td>
    <td>
      <%= f.text_field  :assigned_to,
                        class: "form-control assignment-input" %>
    </td>
    <td>
      <% unless current_page?(controller: 'assignments', action: 'index') %>
        <%= f.select( :status_of,
                      options_for_select(['Pending', 'Complete', 'Reassigned'], @assignment.status_of), {},
                      {class: "form-control form-select assignment-input"} ) %>
      <% else %>
        <%= @assignment.status_of %>
      <% end %>
    </td>
    <td>
      <% unless current_page?(controller: 'assignments', action: 'index') || @assignment.status_of == 'Pending' %>
        <%= f.text_field :review_complete_string,
                          value: (@assignment.review_complete.nil? ?
                                  datetime_placeholder :
                                  @assignment.review_complete.pretty),
                          class: "form-control assignment-input" %>
      <% end %>
    </td>
    <td>
      <%= f.text_field :num_samples,
          class: "form-control assignment-input" %>
    </td>
    <td>
      <%= f.text_field :notes,
          class: "form-control assignment-input" %>
    </td>
    <td>
      <%= f.submit  current_page?(controller: 'assignments', action: 'index') ? "Create" : "Update",
                    class: "btn btn-primary btn-xs assignment-create" %>
    </td>
  </tr>
<% end %>

app/views/assignments/_header_sort.html.erb
<thead>
  <tr>
    <th><%= sortable "assignment_type", "Type" %></th>
    <th><%= sortable "assignment_identifier", "Identifier" %></th>
    <th><%= sortable "pick_up_time", "Pick Up" %></th>
    <th><%= sortable "assigned_to", "Assignee" %></th>
    <th><%= sortable "status_of", "Status" %></th>
    <th><%= sortable "review_complete", "Review" %></th>
    <th>Samples</th>
    <th>Notes & Miscellaneous</th>
    <th>Actions</th>
  </tr>
</thead>

app/views/assignments/_rows.html.erb
<% @assignments.each do |assignment| %>
  <tr class=<%='pending' if assignment.status_of == 'Pending' %>
            <%='reassign' if assignment.status_of == 'Reassigned' %>>
    <td>
      <%= "#{assignment_batch(assignment)} - #{assignment_assay(assignment)}" %>
    </td>
    <td>
      <%= link_to "#{assignment.assignment_identifier}",
                  assignment,
                  class: "btn btn-success btn-block btn-xs" %>
    </td>
    <% unless current_page?(controller: 'home', action: 'index') %>
      <td><%= "#{lab_date(assignment.pick_up_time)} /
              #{mil_time(assignment.pick_up_time)}" %>
      </td>
      <td><%= assignment.assigned_to %></td>
      <td><%= assignment.status_of %></td>
    <% end %>
    <td>
      <% unless assignment.review_complete %>
        <%= link_to 'Complete',
                assignment_path(assignment.id,
                                assignment: { review_complete: Time.now,
                                              status_of: 'Complete'}),
                method: 'patch',
                class: "btn btn-primary btn-xs btn-complete" %>
        <%= link_to 'Reassign',
                new_assignment_reassignment_path(assignment),
                class: "btn btn-primary btn-xs" %>
      <% else %>
        <%= "#{lab_date(assignment.review_complete)} / #{mil_time(assignment.review_complete)}" %>
      <% end %>
    <td><%= "#{assignment.num_samples}" %></td>
    <td>
      <%= link_to 'Notes', assignment_path(assignment), class: "btn btn-primary btn-xs" %>
      <%= link_to "Corrections",  assignment_corrections_path(assignment),
                                  class: "btn btn-primary btn-xs" %>
    </td>
    <td>
      <%= link_to 'Edit', edit_assignment_path(assignment), class: "btn btn-primary btn-xs" %>
      <%= link_to 'Delete', assignment_path(assignment),
                            method: :delete,
                            data: { confirm: 'Are you sure?' },
                            class: "btn btn-danger btn-xs" %>
    </td>
  </tr>
<% end %>

app/views/assignments/edit.html.erb
<h1>Edit Assignment</h1>
<table class="table table-assignments">
  <thead>
    <tr>
      <th>Type</th>
      <th>Identifier</th>
      <th>Pick Up Date/Time</th>
      <th>Assigned To</th>
      <th>Status</th>
      <th>Review Completion</th>
      <th>Number of Samples</th>
      <th>Notes</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= render 'form' %>
  </tbody>
</table>

<%= link_to 'All Assignments', assignments_path, class: "btn btn-info" %>

app/views/assignments/index.html.erb
<h1>Assignments</h1>
<div class="table-responsive">
  <table class="table table-assignments">
    <%= render 'assignments/header_sort' %>
    <tbody>
      <%= render 'assignments/rows' %>
      <%= render 'assignments/form' %>
    </tbody>
  </table>
</div>

app/views/assignments/show.html.erb
<h1>
  <strong>Assignment</strong>
  <br>
  <%= "#{assignment_batch(@assignment)}
      #{assignment_assay(@assignment)} - 
      #{@assignment.assignment_identifier}" %>
</h1>

<table class="table table-assignment-show">
  <tr>
    <th colspan="2">Pick Up</th>
    <td colspan="3"><%= lab_date_at_time(@assignment.pick_up_time) %></td>
  </tr>
  <tr>
    <th colspan="2">Completion</th>
    <td colspan="3">
      <%= @assignment.review_complete.nil? ?
          "Not Complete Yet" :
          lab_date_at_time(@assignment.review_complete) %>
    </td>
  </tr>
  <tr>
    <th colspan="2">Number of Samples</th>
    <td colspan="3"><%= @assignment.num_samples %></td>
  </tr>
  <tr>
    <th colspan="2">Notes</th>
    <td colspan="3">
      <%= @assignment.notes.empty? ? "N/A" : @assignment.notes %>
    </td>
  </tr>
  <% unless @corrections.empty? %>
    <tr class="corrections-row no-hover">
      <th colspan="5">Corrections</th>
    </tr>
    <tr class="corrections-row no-hover">
      <th>Made By</th>
      <th>Missed By</th>
      <th>Type</th>
      <th>Description</th>
      <th>Corrected</th>
    </tr>
    <% @corrections.each do |correction| %>
      <tr class="corrections-row">
        <td><%= correction.made_by %></td>
        <td><%= correction.missed_by %></td>
        <td><%= correction.error_type %></td>
        <td><%= correction.description %></td>
        <td><%= correction.corrected ? "Yes" : "Not Yet" %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<%= link_to "Add a Correction", new_assignment_correction_path(@assignment), class: "btn btn-primary" %>
<%= link_to "Edit Assignment", edit_assignment_path, class: "btn btn-primary" %>