config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'
  
  resources :production_batch_dates, :assays, :assay_batches
  
  resources :assignments do
    resources :corrections
    resources :reassignments
  end
  
end

app/models/reassignment.rb
class Reassignment < ActiveRecord::Base
  belongs_to :assignment
  
  before_save :set_reassigned_from
  after_save :update_assigned_to
  
  def set_reassigned_from
    self.reassigned_from = self.assignment.assigned_to if self.reassigned_from.blank?
  end
  
  def update_assigned_to
    self.assignment.update_assignee_on_reassign!
  end
end

app/controllers/reassignments_controller.rb
class ReassignmentsController < ApplicationController
  before_filter :get_assignment
  
  def index
    @reassignments = @assignment.reassignments.all
  end

  def show
    @reassignment = reassignment_find
  end

  def new
    @reassignment = @assignment.reassignments.new
  end

  def edit
    @reassignment = reassignment_find
  end
  
  def create
    @reassignment = @assignment.reassignments.new(reassignment_params)
    
    if @reassignment.save
      redirect_to assignment_reassignments_path
    else
      render 'new'
    end
  end
  
  def update
    @reassignment = reassignment_find
    
    if @reassignment.update(reassignment_params)
      redirect_to :back
    else
      render 'edit'
    end
  end
  
  def destroy
    @reassignment = reassignment_find
    @reassignment.destroy
    
    redirect_to assignment_reassignments_path
  end
  
  private
    def get_assignment
      @assignment = Assignment.find(params[:assignment_id])
    end
    
    def reassignment_find
      @assignment.reassignments.find(params[:id])
    end
  
    def reassignment_params
      params.require(:reassignment).permit(:reassigned_from,
                                           :reassigned_to)
    end
end

app/helpers/reassignments_helper.rb
module ReassignmentsHelper
end

app/views/reassignments/_form.html.erb
<%= form_for [@assignment, @reassignment], html: {class: "form-horizontal form-new-reassignment"} do |f| %>
  <%= render 'layouts/errors', object: @reassignment %>
  
  
  <% if @reassignment.id && current_page?(controller: 'reassignments', action: 'edit')
  %>
    <div class="form-group">
      <%= f.label :reassigned_from %>
      <%= f.text_field  :reassigned_from,
                        value: @assignment.assigned_to,
                        class: "form-control" %>
    </div>
  <% else %>
    <div><%= @assignment.assigned_to %></div>
  <% end %>
    
  <div class="form-group">  
    <%= f.label :reassigned_to %>
    <%= f.text_field :reassigned_to, class: "form-control" %>
  </div>
  
  <div class="form-group">  
    <%= f.submit  current_page?(controller: 'reassignments', action: 'new') ?
                  "Create" : "Update",
                  class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to "Reassignments for #{assignment_name(@assignment)}",
              assignment_reassignments_path(@assignment),
              class: "btn btn-primary btn-success" %>

app/views/reassignments/edit.html.erb
<h1>Edit Reassignment</h1>

<%= render 'form' %>

app/views/reassignments/index.html.erb
<h1>Reassignments for <%= "#{@assignment.assignment_identifier}"%></h1>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>From</th>
        <th>To</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @reassignments.each do |reassignment| %>
        <tr>
          <td><%= reassignment.reassigned_from %></td>
          <td><%= reassignment.reassigned_to %></td>
          <td>
            <%= link_to 'Edit', edit_assignment_reassignment_path(@assignment.id,
                                                                  reassignment.id),
                                                                  class: "btn btn-primary btn-xs" %>
            <%= link_to 'Delete', assignment_reassignment_path( @assignment.id,
                                                              reassignment.id),
                                                              method: :delete,
                                                              data: { confirm: 'Are you sure?' },
                                                              class: "btn btn-danger btn-xs" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "Add New Reassignment", new_assignment_reassignment_path(@assignment),
                                    class: "btn btn-primary" %>
<div class="btn-separator"></div>
<%= link_to "View Assignment Details", assignment_path(@assignment), class: "btn btn-info" %>

app/views/reassignments/new.html.erb
<h1>Reassignment</h1>

<%= render 'form' %>