config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'
  
  resources :production_batch_dates, :assays, :assay_batches
  
  resources :assignments do
    resources :corrections
    resources :reassignments
  end
  
end

app/models/correction.rb
class Correction < ActiveRecord::Base
  belongs_to :assignment
  
  validates :made_by, :error_type, :description, presence: true
end

app/controllers/corrections_controller.rb
class CorrectionsController < ApplicationController
  load_and_authorize_resource
  
  before_filter :get_assignment
  
  def index
    @corrections = @assignment.corrections.all
  end

  def show
    @correction = correction_find
  end

  def new
    @correction = @assignment.corrections.new
  end

  def edit
    @correction = correction_find
  end
  
  def create
    @correction = @assignment.corrections.new(correction_params)
    
    if @correction.save
      redirect_to assignment_corrections_path
    else
      render 'new'
    end
  end
  
  def update
    @correction = correction_find
    
    if @correction.update(correction_params)
      redirect_to :back
    else
      render 'edit'
    end
  end
  
  def destroy
    @correction = correction_find
    @correction.destroy
    
    redirect_to assignment_corrections_path
  end
  
  private
    def get_assignment
      @assignment = Assignment.find(params[:assignment_id])
    end
    
    def correction_find
      @assignment.corrections.find(params[:id])
    end
  
    def correction_params
      params.require(:correction).permit(:made_by,
                                         :missed_by,
                                         :error_type,
                                         :description,
                                         :corrected)
    end
end

app/helpers/corrections_helper.rb
module CorrectionsHelper
  def correction_assay_batch(correction)
    AssayBatch.find_by_id(correction.assignment.assignment_type)
  end
  
  def correction_batch_num(correction)
    batch_num(correction_assay_batch(correction).production_batch_date.batch_date)
  end
  
  def correction_assay_name(correction)
    correction_assay_batch(correction).assay.name
  end
end

app/views/corrections/_form.html.erb
<%= form_for [@assignment, @correction], html: {class: "form-horizontal form-new-correction"} do |f| %>
  <%= render 'layouts/errors', object: @correction %>
  
  <div class="form-group">
    <%= f.label :made_by %>
    <%= f.text_field :made_by, class: "form-control" %>
  </div>
    
  <div class="form-group">  
    <%= f.label :missed_by %>
    <%= f.text_field :missed_by, class: "form-control" %>
  </div>
  
  <div class="form-group">  
    <%= f.label :error_type %>
    <%= f.text_field :error_type, class: "form-control" %>
  </div>
  
  <div class="form-group">  
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  
  <div class="form-group">  
    <%= f.label 'Corrected?' %>
    <%= f.check_box :corrected %>
  </div>
  
  <div class="form-group">  
    <%= f.submit  current_page?(controller: 'corrections', action: 'new') ?
                  "Create" : "Update",
                  class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to "Corrections for #{assignment_name(@assignment)}",
              assignment_corrections_path(@assignment),
              class: "btn btn-primary btn-success" %>

app/views/corrections/edit.html.erb
<h1>Edit Correction</h1>

<%= render 'form' %>

app/views/corrections/index.html.erb
<h1>Corrections for <%= "#{@assignment.assignment_identifier}"%></h1>
<div class="table-responsive table-corrections">
  <table class="table">
    <thead>
      <tr>
        <th>Made By</th>
        <th>Overlooked By</th>
        <th>Type</th>
        <th>Description</th>
        <th>Corrected?</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @corrections.each do |correction| %>
        <tr>
          <td><%= correction.made_by %></td>
          <td><%= correction.missed_by %></td>
          <td><%= correction.error_type %></td>
          <td><%= correction.description %></td>
          <td>
            <%= correction.corrected ?
                "Yes" :  (link_to 'Mark as Corrected',  assignment_correction_path( @assignment.id,
                                                correction.id,
                                                correction: { corrected: true }),
                                                method: 'patch',
                                                class: "btn btn-primary btn-xs") %>
          </td>
          <td>
            <%= link_to 'Edit',  edit_assignment_correction_path( @assignment.id,
                                                                  correction.id),
                                                                  class: "btn btn-primary btn-xs" %>
            <%= link_to 'Delete', assignment_correction_path( @assignment.id,
                                                              correction.id),
                                                              method: :delete,
                                                              data: { confirm: 'Are you sure?' },
                                                              class: "btn btn-danger btn-xs" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "Add New Correction", new_assignment_correction_path(@assignment),
                                  class: "btn btn-primary" %>
<div class="btn-separator"></div>
<%= link_to "View Assignment Details", assignment_path(@assignment), class: "btn btn-info" %>

app/views/corrections/new.html.erb
<h1>Add New Correction</h1>

<%= render 'form' %>

app/views/corrections/show.html.erb
<h1>Corrections#show</h1>
<p>Find me in app/views/corrections/show.html.erb</p>