config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'
  
  resources :production_batch_dates, :assays, :assay_batches
  
  resources :assignments do
    resources :corrections
    resources :reassignments
  end
  
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2>
      <%= pluralize(object.errors.count, "error") %> prohibited
      this Assay Batch from being saved:
    </h2>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Home", root_path, class: "navbar-brand" %>
      
      <button type="button" class="navbar-toggle collapsed"
                            data-toggle="collapse"
                            data-target="#qapp-navbar-collapse"
                            aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="qapp-navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Assignments", assignments_path %></li>
        <li class="dropdown">
          <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"}, role: "button", aria: {haspopup: "true", expanded: "false"} do %>
            Production Batches<span class="caret"></span>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to "View All Batches", production_batch_dates_path %></li>
            <li><%= link_to "Add a Batch", new_production_batch_date_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"}, role: "button", aria: {haspopup: "true", expanded: "false"} do %>
            Assays<span class="caret"></span>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to "View All Assays", assays_path %></li>
            <li><%= link_to "Add an Assay", new_assay_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"}, role: "button", aria: {haspopup: "true", expanded: "false"} do %>
            Assay Batches<span class="caret"></span>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to "View All Assay Batches", assay_batches_path %></li>
            <li><%= link_to "Add an Assay Batch", new_assay_batch_path %></li>
          </ul>
        </li>
        <li class="sign-in">
          <% if user_signed_in? %>
            Signed in as <strong><%= current_user.username %></strong>
            <%= link_to "Settings", edit_user_registration_path %>
            <%= link_to "Log Out", destroy_user_session_path, :method => :delete %>
          <% else %>
            <%= link_to "Log In", new_user_session_path %>
            <span> or </span>
            <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink="true">
<%= render 'layouts/nav_header' %>

<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> <%= 'alert-success' if message_type == 'notice' %>">
    <button id="remove-alert">
      <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
    </button>
    <p><%= message %></p>
  </div>
<% end %>

<% if user_signed_in? ||
      current_page?(new_user_session_path) ||
      current_page?(new_user_registration_path) %>
  <main>
    <%= yield %>
  </main>
<% else %>
  <main>Please log in to access QApp features.</main>
<% end %>

</body>
</html>